const explorer = 'http://127.0.0.1:4173/';
const header = (label,title,description) => `<section class="page-intro"><span class="eyebrow">${label}</span><h1>${title}</h1><p>${description}</p></section>`;
const card = (label,title,text) => `<article class="info-card"><span class="eyebrow">${label}</span><h3>${title}</h3><p>${text}</p></article>`;
const note = (title,text) => `<aside class="note"><strong>${title}</strong><p>${text}</p></aside>`;
const status = () => `<section class="network-live" aria-label="Local network status"><div><span class="eyebrow">THE NETWORK TODAY</span><span class="status" id="node-status">Checking local node…</span></div><div><span>Latest block</span><strong id="height">—</strong></div><div><span>Current native supply</span><strong id="supply">—</strong></div><a href="${explorer}">Explore the ledger ↗</a></section>`;
const artwork = `<svg viewBox="0 0 440 440" fill="none" aria-hidden="true"><defs><linearGradient id="thread" x1="20" y1="50" x2="410" y2="370" gradientUnits="userSpaceOnUse"><stop stop-color="#e5edc9"/><stop offset="1" stop-color="#769c70"/></linearGradient></defs>${Array.from({length:24},(_,i)=>`<ellipse cx="220" cy="220" rx="${55+i*4.5}" ry="${162-i*2.8}" transform="rotate(${i*7.5} 220 220)" stroke="url(#thread)" stroke-width=".8"/>`).join('')}<circle cx="220" cy="220" r="36" fill="#dce8bd"/><path d="M207 199h10v31h19v10h-29Z" fill="#234c3e"/><circle cx="344" cy="111" r="5" fill="#e5edc9"/><circle cx="83" cy="290" r="3" fill="#e5edc9"/></svg>`;

function home() {
  return `<section class="home-hero"><div class="hero-copy"><span class="eyebrow"><span class="dot"></span> A CREATIVE ECONOMY, IN DEVELOPMENT</span><h1>A network for<br>autonomous<br><em>creativity.</em></h1><p>Luxartium is building the foundations for AI agents and people to create, exchange and collaborate in a shared economy.</p><div class="actions"><a class="button" href="#/how-it-works">Discover Luxartium <span>↗</span></a><a class="quiet-link" href="${explorer}">Explore the testnet →</a></div><div class="hero-caption"><span>01 / FOUNDATION</span><span>A working local blockchain.<br>A larger creative ambition.</span></div></div><div class="hero-art">${artwork}<span class="art-top">LUXARTIUM NETWORK</span><div class="art-bottom"><span>CONNECTED BY CREATION</span><span>LUXAR / v0.1</span></div></div></section>${status()}
    <section class="section"><div class="section-title"><span class="eyebrow">THE IDEA</span><h2>When creators can<br>be economic participants.</h2><p>We’re exploring what happens when autonomous agents can hold resources, make creative decisions, and participate in an economy alongside people.</p></div><div class="card-grid">${card('01 · CREATE','A place for creative work','AI Art Foundry is the creative platform: agents experiment, make artwork and leave a record of their process.')}${card('02 · EXCHANGE','A native network','Luxartium Network provides its own chain and native currency. Today, LUXAR accounts, transfers and fees work on the local testnet.')}${card('03 · PARTICIPATE','An economy to develop','Creative rewards, commissions, licensing and agent commerce are the long-term vision. Their economic rules remain under design.')}</div></section>
    <section class="split-section"><div><span class="eyebrow">A CLEAR STARTING POINT</span><h2>The foundation is live.<br>The vision is unfolding.</h2><p>Build the network, verify its behavior, and make its state visible. Then develop the economic connection with evidence.</p><a class="quiet-link" href="#/roadmap">See the public roadmap →</a></div><div class="capabilities"><div><span class="tag ready">WORKING LOCALLY</span><h3>Accounts. Transfers. A shared record.</h3><p>Native LUXAR, transaction fees, persistent state and a read-only explorer.</p></div><div><span class="tag proposed">IN DEVELOPMENT</span><h3>Creative work as economic activity.</h3><p>Public participation, treasury-funded creative incentives and application integration are future milestones.</p></div></div></section><section class="bottom-cta"><span class="eyebrow">TAKE A CLOSER LOOK</span><h2>A network you can inspect.</h2><p>Every committed transfer leaves a record. Start with the explorer.</p><a class="button light" href="${explorer}">Open the explorer ↗</a></section>`;
}
function about() {
  return header('ABOUT LUXARTIUM','A shared foundation<br>for creative agents.','Luxartium is an experiment in persistent, autonomous economic participation through creative work.') + `<div class="prose"><h2>The ambition</h2><p>The long-term vision is an economy where AI agents hold capital, allocate resources, create cultural artifacts, and collaborate or transact with other agents and humans. Luxartium is the proposed native currency of that economy.</p><p>Humans remain participants: creators, collectors, patrons, agent operators, developers and network validators. The project asks what becomes possible when creative agents can sustain activity across individual tasks.</p><h2>Three connected ideas</h2><div class="card-grid">${card('APPLICATION','AI Art Foundry','The existing agent experimentation and provenance platform. It records creative process, artifacts and human response.')}${card('INFRASTRUCTURE','Luxartium Network','The sovereign blockchain being developed separately. It maintains accounts, balances and transaction history.')}${card('NATIVE CURRENCY','Luxartium · LUXAR','The network’s native currency, called luxar for short. The testnet begins with a fixed 1,000,000,000 LUXAR and no automatic minting.')}</div><h2>Where we are</h2><p>The current release is a local, single-validator development chain. Its transfer loop and restart persistence have been verified. The creative application is not connected to the chain, and test coins have no monetary value or promised conversion to mainnet coins.</p></div>`;
}
function how() {
  return header('HOW IT WORKS','From a signed action<br>to a shared record.','An established blockchain foundation supports the native currency. Creative economics will be developed as a separate layer.') + `<div class="steps">${[['01','An account signs a transaction','A wallet authorizes an action, such as sending LUXAR to another address. The signature establishes who authorized it.'],['02','The network checks and orders it','Cosmos SDK application rules check the transaction. CometBFT coordinates validators to agree on committed blocks.'],['03','The chain records the result','A successful transfer changes balances. Native transaction fees are paid in LUXAR. Included execution failures remain visible in the history.'],['04','Anyone with node access can inspect it','The explorer reads block, transaction and balance data from the node. It does not hold signing keys or transfer funds.']].map(([n,t,p])=>`<article><span class="step">${n}</span><div><h2>${t}</h2><p>${p}</p></div></article>`).join('')}</div>${note('Creative rewards would come from the existing treasury.','The testnet starts with a fixed 1,000,000,000 LUXAR. It has no automatic minting, mint module or module mint authority. Reward eligibility and application integration remain under development.')}<section class="section compact"><div class="section-title"><span class="eyebrow">THE ECONOMIC LAYER</span><h2>Designed with room to learn.</h2><p>Treasury-funded rewards, Studio Credit conversion, commissions, licensing, royalties and agent custody remain design work. The local testnet makes no promises about those future rules.</p></div></section>`;
}
function network() {
  return header('NETWORK','A working local testnet.','Inspect the current development chain and understand its limits.') + status() + `<section class="section compact"><div class="spec-list">${[['Network','luxartium-local-1'],['Native currency','Luxartium · LUXAR (luxar)'],['Precision','1 LUXAR = 1,000,000 uluxar'],['Genesis allocation','1,000,000,000 test LUXAR'],['Minimum transaction fee','0.001 LUXAR, enforced during block execution'],['Consensus','CometBFT with SDK staking; one locally controlled validator'],['Issuance today','No mint module and no module mint authority'],['Participation','Local development only; no published peers or public joining package']].map(([k,v])=>`<div><span>${k}</span><strong>${v}</strong></div>`).join('')}</div></section>${note('This release establishes functionality, not decentralization.','One locally controlled validator provides no fault tolerance. Public participation requires reachable peers, supported releases, independent operators and clear operating policies. The starting allocation is fixed at 1,000,000,000 LUXAR with no automatic minting. Supply may decrease through standard slashing or governance behavior.')}<div class="actions"><a class="button" href="${explorer}">Inspect live records ↗</a><a class="quiet-link" href="#/run-a-node">Learn about running a node →</a></div>`;
}
function runNode() {
  return header('PARTICIPATE','Help operate<br>the network.','Independent node operators are part of Luxartium’s intended path toward a public network.') + note('Public node onboarding is not available yet.','There is no public binary release, shared-network joining command or published seed peer. We will publish these together when a hosted testnet is ready.') + `<div class="card-grid two">${card('VERIFY THE NETWORK','Run a full node','A full node follows the chain, verifies its history and can serve queries. Running one does not automatically give it validator voting power.')}${card('PARTICIPATE IN CONSENSUS','Become a validator','A validator also proposes or signs blocks. Admission, stake distribution, key custody and operator responsibilities need a documented public testnet process.')}</div><section class="prose"><h2>Available to developers today</h2><p>If you already have the source repository, Docker with Linux containers and Python 3.10 or newer, you can build and run a separate local development chain:</p><pre>python localnet.py build
python localnet.py verify
python localnet.py init
python localnet.py start</pre><p><strong>This initializes your own isolated chain.</strong> It does not join this machine’s network. Run initialization only once on a fresh local setup. These commands belong in the repository root.</p><h2>What a joining release will include</h2><ul><li>Versioned node software and published checksums.</li><li>The shared genesis file, chain ID and reachable peer addresses.</li><li>Hardware, networking, synchronization and upgrade instructions.</li><li>A separate validator participation process.</li></ul><a class="quiet-link" href="#/roadmap">Follow the participation milestones →</a></section>`;
}
function roadmap() {
  const phases=[['AVAILABLE LOCALLY','Establish the foundation','Native accounts, transfers, fees, persistent state, public information site and explorer.'],['NEXT','Prove continuous operation','Recovery verification, deployment packaging and a hosted testnet.'],['PLANNED','Open node participation','Publish node releases, shared genesis and instructions for independent operators.'],['PLANNED','Distribute validation','Spread voting power and infrastructure, then practice outages and upgrades.'],['RESEARCH & DESIGN','Connect creative economics','Develop treasury-funded incentives, application integration and rights boundaries.'],['RELEASE GATE','Assess mainnet readiness','Review security, governance, operations and monetary policy before any launch decision.']];
  return header('PUBLIC ROADMAP','One verified step<br>at a time.','An overview of progress and direction. Milestones are not promised dates.') + `<div class="public-roadmap">${phases.map(([s,t,p],i)=>`<article><span class="step">0${i+1}</span><div><span class="tag ${i===0?'ready':'proposed'}">${s}</span><h2>${t}</h2><p>${p}</p></div></article>`).join('')}</div>`;
}
function docs() {
  return header('DOCUMENTATION','Start with the essentials.','A short guide to the current network and its place in Luxartium.') + `<div class="docs-grid"><a href="#/how-it-works">01 <span>Transactions & consensus</span>↗</a><a href="#/network">02 <span>Network parameters</span>↗</a><a href="#/run-a-node">03 <span>Nodes & participation</span>↗</a><a href="${explorer}">04 <span>Explore the ledger</span>↗</a></div><section class="prose"><h2>Common questions</h2>${[['What is LUXAR?','LUXAR is the symbol for Luxartium’s native currency, called luxar for short. On the current local testnet, it pays transfer fees and moves between accounts.'],['Do transfers require another chain’s coin?','Ordinary transfers on this sovereign chain use native LUXAR for fees. They do not require ETH, SOL or another network’s asset.'],['What does an address identify?','A luxar1 address identifies an on-chain account. It is not, by itself, a verified human or agent identity.'],['Can I connect a wallet or buy LUXAR here?','This site provides information and a read-only explorer. Wallet integration, public distribution and market access are not available.'],['Does creating artwork earn currency today?','No. Creative rewards and their eligibility rules remain under development. Any reward distribution uses existing treasury tokens; the testnet does not mint new tokens.'],['Where is the artwork stored?','AI Art Foundry retains its existing storage and provenance systems. No artwork, ownership or rights data has been moved onto this chain.'],['Why do some failed transactions pay fees?','A transaction rejected before inclusion does not pay a fee. A transaction that passes signature and fee processing but fails during message execution still pays its execution fee. The explorer distinguishes results and displays declared fees.']].map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}<h2>Protocol references</h2><p><a href="https://docs.cosmos.network/" target="_blank" rel="noreferrer">Cosmos SDK documentation ↗</a><br><a href="https://docs.cometbft.com/" target="_blank" rel="noreferrer">CometBFT documentation ↗</a></p></section>`;
}
const pages = {home, about, 'how-it-works':how, network, 'run-a-node':runNode, roadmap, docs};
let generation=0;
let networkBusy=false;
async function render() {
  const token=++generation;
  const page=location.hash.replace(/^#\/?/,'') || 'home';
  const view=document.querySelector('#view');
  view.innerHTML = Object.hasOwn(pages,page) ? pages[page]() : header('PAGE UNAVAILABLE','Let’s find your way.','Choose a section from the navigation to explore Luxartium.');
  document.title = `${page==='home'?'A network for autonomous creativity':({'how-it-works':'How it works','run-a-node':'Run a node',about:'About',network:'Network',roadmap:'Roadmap',docs:'Documentation'})[page] || 'Page unavailable'} · Luxartium`;
  document.querySelectorAll('[data-page]').forEach(el=>{if(el.dataset.page===page)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});
  document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');
  if (!document.querySelector('#node-status')) return;
  updateNetwork(token);
}
async function updateNetwork(token) {
  if(networkBusy)return;
  networkBusy=true;
  try {
    const response=await fetch('/api/network',{signal:AbortSignal.timeout(15000)});
    if(!response.ok)throw new Error();
    const data=await response.json();
    if(token!==generation)return;
    const stale=Date.now()-Date.parse(data.time)>30000;
    document.querySelector('#node-status').textContent=data.catching_up?'Node syncing':stale?'No recent blocks':'Local testnet live';
    document.querySelector('#height').textContent=BigInt(data.height).toLocaleString('en-US');
    const units=BigInt(data.supply.amount), fraction=(units%1000000n).toString().padStart(6,'0').replace(/0+$/,'');
    document.querySelector('#supply').textContent=`${(units/1000000n).toLocaleString('en-US')}${fraction?'.'+fraction:''} LUXAR`;
  } catch {
    if(token===generation)document.querySelector('#node-status').textContent='Local node unavailable';
  } finally {networkBusy=false;}
}
document.addEventListener('click',event=>{
  if(event.target.closest('.skip')){event.preventDefault();document.querySelector('#content').focus();}
  if(event.target.closest('.menu-toggle')){const b=document.querySelector('.menu-toggle');b.setAttribute('aria-expanded',String(b.getAttribute('aria-expanded')!=='true'));}
});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
setInterval(()=>{if(!document.hidden && document.querySelector('#node-status'))updateNetwork(generation);},20000);
render();
