// Curated guidance: milestone states are reviewed source edits, not inferred progress.
const phases = [
  ["complete", "WORKING LOCALLY", "Establish the currency", "A sovereign development chain with native LUXAR and a verified transaction loop.", ["Native accounts, balances, transfers and fees", "Fixed 1,000,000,000 LUXAR at genesis; no automatic minting", "Persistent state and signing after restart", "Public home, explorer and authenticated operator workspace"]],
  ["next", "NEXT MILESTONE", "Run a durable hosted testnet", "Prove continuous operation beyond one development machine.", ["Private validator and separate public access node", "Persistent disks, health alerts and controlled releases", "Protected keys and a demonstrated recovery procedure", "Fresh hosted testnet identity and operating notes"]],
  ["planned", "PLANNED", "Let other operators join", "Make the network reproducible and accessible outside this workspace.", ["Versioned binaries or container images with checksums", "Shared genesis, chain ID and reachable seed peers", "Full-node setup, synchronization and upgrade instructions", "Explicit validator admission and test stake distribution"]],
  ["planned", "PLANNED", "Distribute validation", "Test reliability under independent control and real failures.", ["Four equal validators as the first failure-tolerance milestone", "Target 7–10 independent operators for the initial public network", "Spread voting power, providers, regions and key custody", "Practice outages, upgrades and incident response"]],
  ["decision", "DESIGN DECISION", "Define the economic connection", "Decide how creative activity and the app should relate to the currency.", ["Research and specify Proof of Creative Work, if adopted", "Allocate treasury-funded rewards and incentives", "Decide whether Studio Credits connect to LUXAR", "Define artwork, rights and provenance boundaries"]],
  ["decision", "RELEASE GATE", "Assess mainnet readiness", "Review the network, operating model and economics before launch.", ["Independent protocol and operational security review", "Document governance and validator responsibilities", "Verified recovery, monitoring and incident ownership", "Explicit owner authorization for genesis and launch"]],
];
const command = (text) => `<pre class="command"><code>${text}</code></pre>`;
const procedure = (number, title, state, body) => `<section class="panel procedure"><div class="panel-heading"><h2><span class="step-number">${number}</span>${title}</h2><span class="badge ${state === "Available" ? "success" : "planned"}">${state}</span></div><div class="procedure-body">${body}</div></section>`;
const heading = (title, description) => `<div class="page-heading"><div><p class="eyebrow">OPERATOR WORKSPACE</p><h1>${title}</h1><p class="subtitle">${description}</p></div><span class="pill">LOCAL DEVELOPMENT</span></div>`;

export function roadmap() {
  return heading("The path ahead.", "From a working local currency to an independently operated network.") + `<div class="workspace-note"><strong>Current stage: local development</strong><p>These are milestones, not scheduled delivery dates. Public hosting, participation and economic policy require their own implementation and decisions. The validator target is a recommendation awaiting adoption.</p></div><div class="roadmap">${phases.map(([state,label,title,description,items], index) => `<section class="roadmap-card ${state}"><div class="phase-number">0${index + 1}</div><div><span class="eyebrow">${label}</span><h2>${title}</h2><p>${description}</p><ul>${items.map((item) => `<li><span aria-hidden="true">${state === "complete" ? "✓" : "○"}</span>${item}</li>`).join("")}</ul></div></section>`).join("")}</div><div class="network-note"><span>ⓘ</span><p>Count alone does not establish independence. Four equal validators tolerate one offline; seven tolerate two. Consensus requires more than two-thirds of voting power to remain active.</p></div>`;
}

export function processes() {
  return heading("Run the network.", "Repeatable procedures for the local Luxartium testnet.") + `<div class="workspace-note"><strong>Private guidance for the local operator.</strong><p>Run commands from the repository root in your terminal. This workspace requires owner authentication. Funding and node controls remain in the CLI; browser actions, multi-user permissions and a durable operational audit trail are planned.</p></div>` +
    procedure("01", "Start and stop locally", "Available", `<ol><li>Start Docker Desktop and wait for the Linux engine.</li><li>Resume the existing chain:${command("python localnet.py start")}</li><li>Start all three sites in another terminal:${command("python localnet.py sites")}</li><li>Retrieve your operator sign-in key when needed:${command("python localnet.py admin-key")}</li><li>Stop the chain gracefully:${command("python localnet.py stop")}</li></ol><p>The saved chain is already initialized. <code>start</code> preserves its identities and history. Ctrl+C in the sites terminal stops the websites and invalidates admin sessions, without stopping the chain.</p>`) +
    procedure("02", "Check node health", "Available", `<ol><li>Open the <a href="http://127.0.0.1:4173/">explorer overview</a>. Confirm <code>luxartium-local-1</code> and that the latest block advances.</li><li>If blocks stop, inspect status and logs:${command("python localnet.py status\ndocker logs --tail 50 luxartium-local-1")}</li><li>Check Docker and available disk space. After restart, verify existing transactions and balances.</li></ol><p>“Node connected” means a query succeeded. The explorer overview also checks block freshness. Automated alerts and hosted uptime monitoring are planned.</p>`) +
    procedure("03", "Create and fund a test wallet", "Available", `<ol><li>Create a uniquely named test wallet:${command("python localnet.py wallet demo-user\npython localnet.py address demo-user")}</li><li>Replace <code>&lt;address&gt;</code> with its public address:${command("python localnet.py fund &lt;address&gt; 100")}</li><li>Search the returned transaction hash in the <a href="http://127.0.0.1:4173/">explorer</a> and verify the result and recipient balance.</li></ol><p>The faucet transfers existing coins. Amounts are LUXAR; the CLI pays a 0.001-LUXAR fee. For an unknown outcome, query the hash before retrying. Wallets use disposable, unencrypted test keys in Docker storage.</p>`) +
    procedure("04", "Backups and recovery", "Needs implementation", `<p>The Docker volume <code>luxartium-local-1-data</code> survives normal stops and restarts. An independent backup and restore drill has not been implemented or verified.</p><ol><li>Define encrypted backup storage and authorized recovery operators.</li><li>Back up data and signing state consistently with a documented recovery point.</li><li>Practice an isolated restore; verify balances, history and block production.</li><li>Ensure only one instance can sign with a validator key. Old signing state or two running copies can cause conflicting signatures.</li></ol><p>Do not delete the saved volume as a repair step.</p>`) +
    procedure("05", "Build, test and upgrade", "Partly available", `<p>Builds and disposable acceptance tests are available:</p>${command("python localnet.py build\npython localnet.py verify")}<p>The suite cleans up its own network and does not change the saved chain.</p><ol><li>Review the change and acceptance criteria.</li><li>Build and run focused tests plus disposable verification.</li><li>For an existing chain, prepare any required upgrade handler or migration, recovery plan and operator instructions.</li><li>Coordinate and verify the upgrade before applying it to a shared network.</li></ol><p>The operator refuses silent replacement with a different image. SDK upgrade coordination is wired; future handlers still need implementation.</p>`) +
    procedure("06", "Onboard another operator", "Needs implementation", `<p>The software can be built today, but this chain has no published peer port or public joining package.</p><ol><li>Publish a versioned binary or image and checksum.</li><li>Publish shared genesis, chain ID, peers and required ports.</li><li>Initialize a fresh node identity, install the shared genesis, connect and synchronize.</li><li>Verify chain ID, height and connectivity.</li><li>For validators, separately define admission, test stake, independent key custody and responsibilities.</li></ol><p>Full nodes verify the chain. Validators also participate in consensus. More servers under one owner do not create independent governance.</p>`) +
    `<p class="muted fine">References: <a href="https://docs.cosmos.network/hub/latest/validators/security" target="_blank" rel="noreferrer">Cosmos validator security ↗</a> · <a href="https://github.com/cometbft/cometbft/blob/main/docs/core/using-cometbft.md" target="_blank" rel="noreferrer">CometBFT requirements ↗</a></p>`;
}
